// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK8zh_WbkOgp3tpTlav1Pyvy7pSUwhCXY',
    appId: '1:557524235019:web:bd0f8cce7d4734994e680e',
    messagingSenderId: '557524235019',
    projectId: 'basketball-record-82584',
    authDomain: 'basketball-record-82584.firebaseapp.com',
    storageBucket: 'basketball-record-82584.firebasestorage.app',
    measurementId: 'G-RYR1X32KKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbLKIxbJCVcb0KlLKSByjzjVJKQhgtz9s',
    appId: '1:557524235019:android:5fc1668f43badf204e680e',
    messagingSenderId: '557524235019',
    projectId: 'basketball-record-82584',
    storageBucket: 'basketball-record-82584.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcJbfkIZy89HfdkzZPvUuaCgRnzlG5b_8',
    appId: '1:557524235019:ios:d35c14baad9cfb584e680e',
    messagingSenderId: '557524235019',
    projectId: 'basketball-record-82584',
    storageBucket: 'basketball-record-82584.firebasestorage.app',
    iosBundleId: 'com.soogil.basketball.record',
  );
}
